### ISSUE TITLE
"sealed hardware" only in German but not in English

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nitrokey-documentation#148]
[This German](https://docs.nitrokey.com/de/nitropc/sealed-hardware) does exists but the [original English](https://docs.nitrokey.com/nitropc/sealed-hardware) doesn't exist. Check if the German page should still exists or if it's left over from an older stage. Or add the English page to be consistent.

**Comment by mmerklinger** [comment]
This issue occurs because the directories of the products contain `.rst.inc` files. These are then included into the actual `.rst` documentation files. The include files are not parsed by Sphinx, but Weblate translates them. Hence, they exist in all translation except English.

The easiest solution would be to exclude `.rst.inc` files from the translation in Weblate.

**Comment by jans23** [comment]
Seems to be solved by now.
