### ISSUE TITLE
Incorrect documentation of pivy-tool

### ISSUE THREAD

**Issue by anotherbridge** [Nitrokey/nitrokey-documentation#199]
After going through the setup of creating a certificate on a Nitrokey 3 (firmware v1.5.0) described in https://docs.nitrokey.com/nitrokey3/windows/piv I was not able to get a Nitrokey recognized by pivy tool. It is always prompting `pivy-tool: no PIV cards/tokens found`. Are there any steps missing in the documentation? If not I would like to have the documentation clarified on that usage.  
FYI: I tested this on several Linux distributions as well as macOS and got the same result everytime.

Further the documentation states the usage as `pivy-tool <operation> [options]` while from pivy the correct usage is `pivy-tool [options] <operation>`.

**Comment by sosthene-nitrokey** [comment]
Hi!

PIV is currently not considered stable and is therefore only available on the stable releases of the firmware.
To make piv functionality available, you will need to install a `test` release, marked as `test` in the name. The latest such firmware release is version [`1.5.0-test.20231030`](https://github.com/Nitrokey/nitrokey-3-firmware/releases/tag/v1.5.0-test.20231030).

You can install it with `nitropy nk3 update --version v1.5.0-test.20231030`.

Note that since these releases are considered unstable, updating the firmware might require reset of the unstable functionality, such as PIV.

This is documented at https://docs.nitrokey.com/nitrokey3/windows/firmware-update#firmware-release-types

**Comment by anotherbridge** [comment]
And could you please also document the default PIN and PUK for the PIV feature? If it's desired I can of course open a dedicated issue for that for easier future reference.

**Comment by daringer** [comment]
see https://github.com/Nitrokey/nitrokey-3-firmware/issues/389

**Comment by jans23** [comment]
I think the documentation is up to date and thus this issue is solved.
